export interface AvatarOption {
  id: string;
  label: string;
}

// Open Peeps head (hair/hat) styles — from @dicebear/open-peeps
export const HEAD_OPTIONS: AvatarOption[] = [
  { id: 'short1', label: 'Short' },
  { id: 'short2', label: 'Short 2' },
  { id: 'short3', label: 'Short 3' },
  { id: 'short4', label: 'Short 4' },
  { id: 'short5', label: 'Short 5' },
  { id: 'shaved1', label: 'Shaved' },
  { id: 'shaved2', label: 'Shaved 2' },
  { id: 'shaved3', label: 'Shaved 3' },
  { id: 'flatTop', label: 'Flat Top' },
  { id: 'flatTopLong', label: 'Flat Top Long' },
  { id: 'pomp', label: 'Pompadour' },
  { id: 'mohawk', label: 'Mohawk' },
  { id: 'mohawk2', label: 'Mohawk 2' },
  { id: 'bangs', label: 'Bangs' },
  { id: 'bangs2', label: 'Bangs 2' },
  { id: 'medium1', label: 'Medium' },
  { id: 'medium2', label: 'Medium 2' },
  { id: 'medium3', label: 'Medium 3' },
  { id: 'mediumBangs', label: 'Medium Bangs' },
  { id: 'mediumBangs2', label: 'Med. Bangs 2' },
  { id: 'mediumBangs3', label: 'Med. Bangs 3' },
  { id: 'mediumStraight', label: 'Med. Straight' },
  { id: 'long', label: 'Long' },
  { id: 'longBangs', label: 'Long Bangs' },
  { id: 'longCurly', label: 'Long Curly' },
  { id: 'longAfro', label: 'Long Afro' },
  { id: 'afro', label: 'Afro' },
  { id: 'cornrows', label: 'Cornrows' },
  { id: 'cornrows2', label: 'Cornrows 2' },
  { id: 'dreads1', label: 'Dreads' },
  { id: 'dreads2', label: 'Dreads 2' },
  { id: 'twists', label: 'Twists' },
  { id: 'twists2', label: 'Twists 2' },
  { id: 'bantuKnots', label: 'Bantu Knots' },
  { id: 'bun', label: 'Bun' },
  { id: 'bun2', label: 'Bun 2' },
  { id: 'buns', label: 'Double Bun' },
  { id: 'grayBun', label: 'Gray Bun' },
  { id: 'grayMedium', label: 'Gray Medium' },
  { id: 'grayShort', label: 'Gray Short' },
  { id: 'hatBeanie', label: 'Beanie' },
  { id: 'hatHip', label: 'Hip Hat' },
  { id: 'hijab', label: 'Hijab' },
  { id: 'turban', label: 'Turban' },
  { id: 'bear', label: 'Bear' },
  { id: 'noHair1', label: 'Bald' },
  { id: 'noHair2', label: 'Bald 2' },
  { id: 'noHair3', label: 'Bald 3' },
];

export const FACE_OPTIONS: AvatarOption[] = [
  { id: 'smile', label: 'Smile' },
  { id: 'smileBig', label: 'Big Smile' },
  { id: 'smileLOL', label: 'LOL' },
  { id: 'smileTeethGap', label: 'Teeth' },
  { id: 'calm', label: 'Calm' },
  { id: 'awe', label: 'Awe' },
  { id: 'cheeky', label: 'Cheeky' },
  { id: 'cute', label: 'Cute' },
  { id: 'driven', label: 'Focused' },
  { id: 'lovingGrin1', label: 'Loving' },
  { id: 'lovingGrin2', label: 'Loving 2' },
  { id: 'eatingHappy', label: 'Eating' },
  { id: 'explaining', label: 'Explaining' },
  { id: 'hectic', label: 'Hectic' },
  { id: 'serious', label: 'Serious' },
  { id: 'solemn', label: 'Solemn' },
  { id: 'suspicious', label: 'Suspicious' },
  { id: 'blank', label: 'Blank' },
  { id: 'eyesClosed', label: 'Eyes Closed' },
  { id: 'tired', label: 'Tired' },
  { id: 'old', label: 'Old' },
  { id: 'sad', label: 'Sad' },
  { id: 'concerned', label: 'Concerned' },
  { id: 'concernedFear', label: 'Fearful' },
  { id: 'fear', label: 'Fear' },
  { id: 'contempt', label: 'Contempt' },
  { id: 'rage', label: 'Rage' },
  { id: 'veryAngry', label: 'Very Angry' },
  { id: 'angryWithFang', label: 'Angry Fang' },
  { id: 'cyclops', label: 'Cyclops' },
  { id: 'monster', label: 'Monster' },
];

export const ACCESSORY_OPTIONS: AvatarOption[] = [
  { id: 'glasses', label: 'Glasses' },
  { id: 'glasses2', label: 'Glasses 2' },
  { id: 'glasses3', label: 'Glasses 3' },
  { id: 'glasses4', label: 'Glasses 4' },
  { id: 'glasses5', label: 'Glasses 5' },
  { id: 'sunglasses', label: 'Sunglasses' },
  { id: 'sunglasses2', label: 'Sunglasses 2' },
  { id: 'eyepatch', label: 'Eyepatch' },
];

export const FACIAL_HAIR_OPTIONS: AvatarOption[] = [
  { id: 'chin', label: 'Chin' },
  { id: 'goatee1', label: 'Goatee' },
  { id: 'goatee2', label: 'Goatee 2' },
  { id: 'full', label: 'Full Beard' },
  { id: 'full2', label: 'Full Beard 2' },
  { id: 'full3', label: 'Full Beard 3' },
  { id: 'full4', label: 'Full Beard 4' },
  { id: 'moustache1', label: 'Moustache 1' },
  { id: 'moustache2', label: 'Moustache 2' },
  { id: 'moustache3', label: 'Moustache 3' },
  { id: 'moustache4', label: 'Moustache 4' },
  { id: 'moustache5', label: 'Moustache 5' },
  { id: 'moustache6', label: 'Moustache 6' },
  { id: 'moustache7', label: 'Moustache 7' },
  { id: 'moustache8', label: 'Moustache 8' },
  { id: 'moustache9', label: 'Moustache 9' },
];

export const SKIN_TONES = [
  { id: 'tone-1', label: 'Ivory', hex: '#FDDBB4' },
  { id: 'tone-2', label: 'Peach', hex: '#F2C2A0' },
  { id: 'tone-3', label: 'Sand', hex: '#E8B88A' },
  { id: 'tone-4', label: 'Caramel', hex: '#C68642' },
  { id: 'tone-5', label: 'Mocha', hex: '#8D5524' },
  { id: 'tone-6', label: 'Espresso', hex: '#4A2912' },
];

export const HAIR_COLORS = [
  { id: 'hc-1', label: 'Black', hex: '#1a1a1a' },
  { id: 'hc-2', label: 'Dark Brown', hex: '#3b1e08' },
  { id: 'hc-3', label: 'Brown', hex: '#6B3A2A' },
  { id: 'hc-4', label: 'Blonde', hex: '#D4A543' },
  { id: 'hc-5', label: 'Auburn', hex: '#922724' },
  { id: 'hc-6', label: 'Red', hex: '#c0392b' },
  { id: 'hc-7', label: 'Silver', hex: '#B0B0B0' },
  { id: 'hc-8', label: 'White', hex: '#f0f0f0' },
  { id: 'hc-9', label: 'Blue', hex: '#2563EB' },
  { id: 'hc-10', label: 'Pink', hex: '#EC4899' },
  { id: 'hc-11', label: 'Purple', hex: '#7c3aed' },
  { id: 'hc-12', label: 'Teal', hex: '#0d9488' },
];

export const CLOTHING_COLORS = [
  { id: 'cc-1', label: 'Charcoal', hex: '#374151' },
  { id: 'cc-2', label: 'Navy', hex: '#1e3a5f' },
  { id: 'cc-3', label: 'Indigo', hex: '#4338ca' },
  { id: 'cc-4', label: 'Forest', hex: '#15803d' },
  { id: 'cc-5', label: 'Scarlet', hex: '#b91c1c' },
  { id: 'cc-6', label: 'Purple', hex: '#7c3aed' },
  { id: 'cc-7', label: 'Teal', hex: '#0d9488' },
  { id: 'cc-8', label: 'Slate', hex: '#64748b' },
  { id: 'cc-9', label: 'Orange', hex: '#c2410c' },
  { id: 'cc-10', label: 'Pink', hex: '#be185d' },
  { id: 'cc-11', label: 'Yellow', hex: '#a16207' },
  { id: 'cc-12', label: 'White', hex: '#e2e8f0' },
];

export const BACKGROUND_COLORS = [
  { id: 'bg-1', label: 'Midnight', hex: '#020617' },
  { id: 'bg-2', label: 'Dark', hex: '#0f172a' },
  { id: 'bg-3', label: 'Navy', hex: '#1e3a5f' },
  { id: 'bg-4', label: 'Forest', hex: '#14532d' },
  { id: 'bg-5', label: 'Maroon', hex: '#4a0e0e' },
  { id: 'bg-6', label: 'Indigo', hex: '#1e1b4b' },
  { id: 'bg-7', label: 'Slate', hex: '#334155' },
  { id: 'bg-8', label: 'Deep Purple', hex: '#2e1065' },
  { id: 'bg-9', label: 'Zinc', hex: '#18181b' },
  { id: 'bg-10', label: 'Stone', hex: '#1c1917' },
];
